### ISSUE TITLE
ActivityのLaunch時に落ちる問題について

### ISSUE THREAD

**Issue by mizofumi0411** [NanJ-Dev/NanJ-AA#1]
さっきなんJでプルリク送る言った者です、取り急ぎ確認するとここで落ちてる。
https://github.com/NanJ-Dev/NanJ-AA/blob/master/app/src/main/java/com/nanj/aa/MainActivity.java#L10
LinerLayoutに問題がないか確認してみて欲しい。
まだ電車の中だから、帰宅後も解決してなかったらプルリク送るね。

**Comment by NanJ-Dev** [comment]
issueありがとうございます‼
本当に送ってくれるとは思いませんでした。

取り敢えずactivity_main.xmlの怪しいと思った
https://github.com/NanJ-Dev/NanJ-AA/commit/2e600705c9cb47e1c97ccbebd9a2be3b28b65f72#diff-03fed2eb51192f2b91ea135dd4d65600
と
https://github.com/NanJ-Dev/NanJ-AA/commit/2e600705c9cb47e1c97ccbebd9a2be3b28b65f72#diff-03fed2eb51192f2b91ea135dd4d65600
を削除してみましたが、結局起動時にクラッシュしてしまいます。

↑の変更後のapkです
http://thuploader.orz.hm/miniup/?mode=dl&id=7806&original=1

**Comment by NanJ-Dev** [comment]
Commitのurl間違えました😓
https://github.com/NanJ-Dev/NanJ-AA/commit/5c6a21038eb1fa71a8667b38000ffdd9e3897b98
と
https://github.com/NanJ-Dev/NanJ-AA/commit/2e600705c9cb47e1c97ccbebd9a2be3b28b65f72
です

**Comment by mizofumi0411** [comment]
帰宅したのでじっくり見てみました。

今回はAndroid Support Libraryではなく、AndroidXを使用してるんですね。
https://github.com/NanJ-Dev/NanJ-AA/blob/master/app/build.gradle#L17-L18

LogCatでは下記のとおり、暗示的に `android.view.Linearlayout` を参照しようとしてます。
```
 Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.Linearlayout" on path: DexPathList[[zip file "/data/app/com.nanj.aa-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nanj.aa-2/lib/x86, /system/lib, /vendor/lib]]
```
つまり、レイアウトファイル`activity_main.xml`で指定されているLinearLayoutは `android.view.Linearlayout` を参照していると言えます。

しかし、AndroidXを使用してMainActivityを組んでいるので `android.view.Linearlayout` が無いよ！という事になります。
https://github.com/NanJ-Dev/NanJ-AA/blob/master/app/src/main/java/com/nanj/aa/MainActivity.java#L4

ということで、`activity_main.xml` で指定してる LinearLayoutを明示的にAndroidXのものに置き換えてあげると動くと思います。

ひとまずプルリク作りますねー

**Comment by NanJ-Dev** [comment]
なんて優しい方なんだ…😍
こんな人生終わってるニートが作ってるプロジェクトとも言えないクソにアドバイスを下さりありがとうございます‼
プルリク待ってます‼

**Comment by mizofumi0411** [comment]
そんなに自虐的にならないで下さい！
CI/CDを意識してGitHubActionsも活用されてますし素晴らしいと思います。

プルリク投げましたので確認してくださいなー
https://github.com/NanJ-Dev/NanJ-AA/pull/2

![スクリーンショット 2020-06-13 20 55 05](https://user-images.githubusercontent.com/2261381/84568115-40255e80-adb8-11ea-908e-0a5dcae20133.png)

**Comment by mizofumi0411** [comment]
もし追加で質問などありましたらTwitterとかでも言って頂ければとー

**Comment by NanJ-Dev** [comment]
プルリクマージしました。
あと実機でも動作確認できました。
![Screenshot_20200613-205835](https://user-images.githubusercontent.com/66310094/84568203-be820080-adb8-11ea-9392-a57874bdc8e6.png)
なんJでこんな良い人に出会えるとは思いませんでした‼
ありがとうございます‼

**Comment by mizofumi0411** [comment]
解決されたようなので閉じますー
